### ISSUE TITLE
v-qrcode

### ISSUE THREAD

**Issue by andri-sudarmawijaya** [bantenprov/tanara#35]
https://vuejsfeed.com/blog/a-qrcode-component-for-vue-js
we will used in transaction status.

**Comment by ChemprenX** [comment]
[0001-issue-300692512.patch.txt](https://github.com/bantenprov/tanara/files/1771631/0001-issue-300692512.patch.txt)

**Comment by andri-sudarmawijaya** [comment]
![issuecomment-369622693-fd494e80-b158-4005-882e-4a288dd59071](https://user-images.githubusercontent.com/28795941/36899757-19b2fccc-1e53-11e8-9847-60eac890b87e.jpg)
![issuecomment-369622693-0c5e57ff-fd2a-472e-8db8-a39c31113175](https://user-images.githubusercontent.com/28795941/36899758-19e7d73a-1e53-11e8-9e9b-9b46f60118f5.jpg)

Please, review https://github.com/bantenprov/tanara/files/1771631/0001-issue-300692512.patch.txt

**Comment by igoynawamreh** [comment]
Use https://github.com/xkeshi/vue-qrcode for Vue 2.
