### ISSUE TITLE
some feature not working

### ISSUE THREAD

**Issue by badueny** [bantenprov/tanara#46]
feature scroll pada Nav dan view logout tidak tampil pada saat countdown dipasang

**Comment by badueny** [comment]
fixed simpan script di atas
<script>
import { mapGetters } from 'vuex';
import Countdown from 'vuejs-countdown';

export default {
  components: { Countdown },
  computed: mapGetters({
.....

**Comment by igoynawamreh** [comment]
Use `<countdown>`.

Example: 

https://github.com/bantenprov/tanara/blob/8fa5e51c4a02dde80b0f1bcaa7d62ab3b36546a4/resources/assets/js/components/views/DemoVueCountdown.vue#L11
