### ISSUE TITLE
Tanara not  on fresh install

### ISSUE THREAD

**Issue by andri-sudarmawijaya** [bantenprov/tanara#48]
Tanara not  on fresh install reff latest commit [ Remove unused oauth providers](https://github.com/bantenprov/tanara/commit/2079cd1e068e70e3bb2adb46614743a2123be890)
![screenshot from 2018-03-22 07-19-39](https://user-images.githubusercontent.com/28795941/37744397-77fd1df0-2da1-11e8-9244-0bef2b6006f8.png)

**Comment by igoynawamreh** [comment]
Local? use `npm run dev`.
